name: First Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'World'
      tag:
        description: 'Tag'
        required: true
        default: 'v1'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print multiple command
        run: |
          echo "First output"
          echo "Second output"
          echo "Third output"
          echo "Test Branch/feat/001"
          echo "sha: ${{ github.sha }}"
          echo "run_number: ${{ github.run_number }}"
          echo "date: $(date +'%Y%m%d%H%M%S%N%z')"
